# Database credentials
db_host = "localhost"           # Usually "localhost" if MySQL is on the same machine
db_user = "root"                # Your MySQL username
db_password = "root"      # Your MySQL password
db_name = "pharmacy_erp"        # Your database name
